main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('vinyls/', views.vinyls_index, name='index'),
    path('vinyls/<int:vinyl_id>/', views.vinyls_detail, name='detail'),
    path('vinyls/create/', views.VinylCreate.as_view(), name='vinyls_create'),
    # CBVs that work with individual model instances expect to find a named parameter of 'pk'
    path('vinyls/<int:pk>/update/', views.VinylUpdate.as_view(), name='vinyls_update'),
    path('vinyls/<int:pk>/delete/', views.VinylDelete.as_view(), name='vinyls_delete'),
    path('vinyls/<int:vinyl_id>/add_purchase/', views.add_purchase, name='add_purchase'),
    # person URLs
    path('buyers/', views.BuyerList.as_view(), name='buyers_index'),
    path('buyers/<int:pk>', views.BuyerDetail.as_view(), name='buyers_detail'),
    path('buyers/create', views.BuyerCreate.as_view(), name='buyers_create'),
    path('buyers/<int:pk>/update/', views.BuyerUpdate.as_view(), name='buyers_update'),
    path('buyers/<int:pk>/delete/', views.BuyerDelete.as_view(), name='buyers_delete'),
    # M:M relationship between Buyer and Vinyl
    path('vinyls/<int:vinyl_id>/assoc_buyer/<int:buyer_id>/', views.assoc_buyer, name='assoc_buyer'),
]

vinylcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator

OWNS = (
    ('Y', 'Yes'),
    ('N', 'No'),
)

class Buyer(models.Model):
    name=models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('buyers_detail', kwargs={'pk':self.id})
        
# Create your models here.
class Vinyl(models.Model):
    name = models.CharField(max_length=100)
    artist = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    year = models.IntegerField()
    buyers = models.ManyToManyField(Buyer)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'vinyl_id': self.id})

class Purchase(models.Model):
    date = models.DateField('Date')
    price = models.PositiveIntegerField(validators=[MinValueValidator(0)])
    own = models.CharField(
        max_length=1,
        choices = OWNS,
        default = OWNS[1][0]
    )
    
    # Create a vinyl_id FK
    vinyl = models.ForeignKey(Vinyl, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.get_own_display()} on {self.date}'

    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Purchase

class PurchaseForm(ModelForm):
    class Meta:
        model = Purchase
        fields = ['date', 'price', 'own']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponse

from .models import Vinyl, Buyer
from .forms import PurchaseForm

# Create your views here.
def home(request):
    # return HttpResponse('Home working')
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def vinyls_index(request):
    vinyls = Vinyl.objects.all()
    # render 'index.html' from folder 'vinyls'
    return render(request, 'vinyls/index.html', {'vinyls': vinyls})

def vinyls_detail(request, vinyl_id):
    vinyl = Vinyl.objects.get(id=vinyl_id)

    has_not_purchased = Buyer.objects.exclude(id__in = vinyl.buyers.all().values_list('id'))

    purchase_form = PurchaseForm
    return render(request, 'vinyls/detail.html', {
        'vinyl': vinyl,
        'purchase_form': purchase_form,
        'buyers': has_not_purchased    
    })

def add_purchase(request, vinyl_id):
    # create ModelForm using 'request.POST'
    form = PurchaseForm(request.POST)
    # validate form
    if form.is_valid():
        # don't save to db until vinyl_id is assigned
        new_purchase = form.save(commit=False)
        new_purchase.vinyl_id = vinyl_id
        new_purchase.save()
    return redirect('detail', vinyl_id=vinyl_id)

def assoc_buyer(request, vinyl_id, buyer_id):
    Vinyl.objects.get(id=vinyl_id).buyers.add(buyer_id)
    return redirect('detail', vinyl_id=vinyl_id)

class VinylCreate(CreateView):
    model = Vinyl
    # include all fields from Vinyl in 'models.py'
    # fields = '__all__'
    fields = ['name', 'artist', 'genre', 'year']
    # success_url = '/vinyls/'

class VinylUpdate(UpdateView):
    model = Vinyl
    # only allow user to update certain fields of Vinyl
    fields = ['artist', 'genre', 'year']

class VinylDelete(DeleteView):
    model = Vinyl
    success_url = '/vinyls/'

class BuyerCreate(CreateView):
    model=Buyer
    fields = ('name',)

class BuyerUpdate(UpdateView):
    model=Buyer
    fields=('name',)

class BuyerDelete(DeleteView):
    model=Buyer
    success_url = '/buyers/'

class BuyerDetail(DetailView):
    model = Buyer
    template_name = 'buyers/detail.html'

class BuyerList(ListView):
    model = Buyer
    template_name = 'buyers/index.html'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content%}
<h1>About Page</h1>
<hr/>
<p>Vinyl collection, and list of people who have bought them</p>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vinyl Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'vinylcollector/style.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li>
                        <a href="/" class="left brand-logo">&nbsp;&nbsp;Vinyl Collector</a>
                    </li>
                </ul>
                <ul class="right">
                    <li><a href="{% url 'about' %}">About</a></li>
                    <li><a href="{% url 'vinyls_create' %}">Add Vinyl</a></li>
                    <li><a href="{% url 'index' %}">View All Vinyl</a></li>
                    <li><a href="{% url 'buyers_create' %}">Add Buyer</a></li>
                    <li><a href="{% url 'buyers_index' %}">View All Buyers</a></li>
                </ul>
            </div>
        </nav>
    </header>

    <main class="container" style="text-align: center;">{% block content %} {% endblock %}</main>
    
    <footer class="page-footer">
        <div class="right">
            All Rights Reserved, &copy; 2022 Vinyl Collector &nbsp;
        </div>
    </footer>
</body>

</html>

main_app/templates/buyers/detail.html
{% extends 'base.html' %}

{% block content %}

<h1>Buyer Details</h1>

<div class="card">
    <a href="{% url 'buyers_detail' buyer.id %}">
        <div class="card-content">
            <span class="card-title">{{ buyer.name }}</span>
        </div>
        <div class="card-action">
            <a href="{% url 'buyers_update' buyer.id %}">Edit</a>
            <a href="{% url 'buyers_delete' buyer.id %}">Delete</a>
        </div>
    </a>
</div>

{% endblock %}

main_app/templates/buyers/index.html
{% extends 'base.html' %}

{% block content %}

<h1>Buyers List</h1>
{% for buyer in buyer_list %}
<div class="card">
    <a href="{% url 'buyers_detail' buyer.id %}">
        <div class="card-content">
            <span class="card-title">{{ buyer.name }}</span>
        </div>
    </a>
</div>
{% endfor %}
{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>Vinyl Collector Home</h1>
<hr/>
<img src="https://imgur.com/cMsHWex.jpg" style="width: 80%; text-align: center;">
{% endblock %}

main_app/templates/main_app/buyer_confirm_delete.html
{% extends 'base.html' %} 
{% block content %}

<h1>Delete Buyer</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' buyer.id %}">Cancel</a>
</form>

{% endblock %}

main_app/templates/main_app/buyer_form.html
{% extends 'base.html' %}

{% block content %}

{% if buyer %}
<h1>Edit {{ buyer.name }}'s information</h1>
{% else %}
<h1>Add a new Buyer</h1>
{% endif %}

<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="{% if buyer %} Edit {% else %} Add {% endif %}"class="btn">
</form>

{% endblock %}

main_app/templates/main_app/vinyl_confirm_delete.html
{% extends 'base.html' %} 
{% block content %}
<h1>Delete Vinyl</h1>

<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' vinyl.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/vinyl_form.html
{% extends 'base.html' %} 
{% block content %}

<!-- since name wasn't included in fields of VinylUpdate -->
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Vinyl</h1>
{% endif %}

<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}

main_app/templates/vinyls/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Vinyl Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ vinyl.name }}</span>
                <p>Artist: {{ vinyl.artist }}</p>
                <p>Genre: {{ vinyl.genre }}</p>
                <p>Year: {{ vinyl.year }}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'vinyls_update' vinyl.id %}">Edit</a>
                <a href="{% url 'vinyls_delete' vinyl.id %}">Delete</a>
            </div>
        </div>
    </div>
    <div class="col s6">
        <form action="{% url 'add_purchase' vinyl.id %}" method="post" style="text-align: start;">
            {% csrf_token %}
            {{ purchase_form.as_p }}
            <input type="submit" class="btn" value="Add Purchase" />
        </form>
        <table class="striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Price</th>
                    <th>Own</th>
                </tr>
            </thead>
            <tbody>
                {% for purchase in vinyl.purchase_set.all %}
                <tr>
                    <td>{{purchase.date}}</td>
                    <td>{{purchase.price}}</td>
                    <td>{{purchase.get_own_display}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<hr />
<div class="row">
    <div class="col s6">
        <h3>{{ vinyl.name }}'s Buyers</h3>
        {% if vinyl.buyers.count %} {% for buyer in vinyl.buyers.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    <span>{{ buyer.name }}</span>
                </span>
            </div>
        </div>
        {% endfor %} {% else %}
        <h5>No Buyers :(</h5>
        {% endif %}
    </div>

    <div class="col s6">
        <h3>Available Buyers</h3>
        {% if buyers.count %}
        {% for buyer in buyers.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    <span>{{ buyer.name }}</span>
                </span>
            </div>
            <div class="card-action">
                <form action="{% url 'assoc_buyer' vinyl.id buyer.id %}" method="post" style="text-align: start;">
                    {% csrf_token %}
                    <button type="submit" class="btn">Add</button>
                </form>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>{{vinyl.name}} has been purchased from all Buyers</h5>
        {% endif %}
    </div>
</div>

<script>
    let dateEl = document.getElementById('id_date')
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    })

    let selectEl = document.getElementById('id_own')
    M.FormSelect.init(selectEl)
</script>
{% endblock %}

main_app/templates/vinyls/index.html
{% extends 'base.html' %}
{% block content %}

{% for vinyl in vinyls %}
<div class="card">
    <!-- <a href="/vinyls/{{ vinyl.id }}"> -->
        <!-- url 'some-url-name' arg1 arg2... -->
    <a href="{% url 'detail' vinyl.id %}">
        <div class="card-content">
            <p> {{vinyl.name}} </p>
            <!-- <p> Artist: {{vinyl.artist}} </p> -->
            <!-- <p> Genre: {{vinyl.genre}} </p> -->
        </div>
    </a>
</div>

{% endfor %}
{% endblock %}